/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (autogen-fsm.h)
 *
 *  It has been AutoGen-ed
 *  From the definitions    autogen.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 *  This file enumerates the states and transition events for a FSM.
 *
 *  te_smtp_fsm_state
 *      The available states.  FSS_INIT is always defined to be zero
 *      and FSS_INVALID and FSS_DONE are always made the last entries.
 *
 *  te_smtp_fsm_event
 *      The transition events.  These enumerate the event values used
 *      to select the next state from the current state.
 *      SMTP_FSM_EV_INVALID is always defined at the end.
 */
#ifndef AUTOFSM_AUTOGEN_FSM_H_GUARD
#define AUTOFSM_AUTOGEN_FSM_H_GUARD 1
/**
 *  Finite State machine States
 *
 *  Count of non-terminal states.  The generated states INVALID and DONE
 *  are terminal, but INIT is not  :-).
 */
#define SMTP_FSM_STATE_CT  21
typedef enum {
    SMTP_FSM_ST_INIT,
    SMTP_FSM_ST_SMTP_ERROR,
    SMTP_FSM_ST_PREPARE_SOCKET_CONNECTION,
    SMTP_FSM_ST_CONNECT,
    SMTP_FSM_ST_RECEIVE_SMTP_GREETING,
    SMTP_FSM_ST_SEND_EHLO,
    SMTP_FSM_ST_RECEIVE_EHLO_RESPONSE,
    SMTP_FSM_ST_SEND_MAIL_FROM,
    SMTP_FSM_ST_RECEIVE_MAIL_FROM_RESPONSE,
    SMTP_FSM_ST_SEND_RCPT_TO,
    SMTP_FSM_ST_RECEIVE_RCPT_TO_RESPONSE,
    SMTP_FSM_ST_SEND_DATA,
    SMTP_FSM_ST_RECEIVE_DATA_RESPONSE,
    SMTP_FSM_ST_SEND_LETTER,
    SMTP_FSM_ST_RECEIVE_LETTER_RESPONSE,
    SMTP_FSM_ST_SEND_QUIT,
    SMTP_FSM_ST_RECEIVE_QUIT_RESPONSE,
    SMTP_FSM_ST_DISPOSING_SOCKET,
    SMTP_FSM_ST_NEXT_LETTER,
    SMTP_FSM_ST_SEND_RSET,
    SMTP_FSM_ST_RECEIVE_RSET_RESPONSE,
    SMTP_FSM_ST_INVALID,
    SMTP_FSM_ST_DONE
} te_smtp_fsm_state;

/**
 *  Finite State machine transition Events.
 *
 *  Count of the valid transition events
 */
#define SMTP_FSM_EVENT_CT 20
typedef enum {
    SMTP_FSM_EV_CONNECTION,
    SMTP_FSM_EV_HANDLE_SMTP_GREETING,
    SMTP_FSM_EV_HANDLE_SEND_EHLO,
    SMTP_FSM_EV_HANDLE_EHLO_RESPONSE,
    SMTP_FSM_EV_HANDLE_SEND_MAIL_FROM,
    SMTP_FSM_EV_HANDLE_MAIL_FROM_RESPONSE,
    SMTP_FSM_EV_HANDLE_SEND_RCPT_TO,
    SMTP_FSM_EV_HANDLE_RCPT_TO_RESPONSE,
    SMTP_FSM_EV_HANDLE_SEND_DATA,
    SMTP_FSM_EV_HANDLE_DATA_RESPONSE,
    SMTP_FSM_EV_HANDLE_SEND_LETTER,
    SMTP_FSM_EV_HANDLE_LETTER_RESPONSE,
    SMTP_FSM_EV_HANDLE_SEND_QUIT,
    SMTP_FSM_EV_HANDLE_QUIT_RESPONSE,
    SMTP_FSM_EV_HANDLE_DISPOSING_SOCKET,
    SMTP_FSM_EV_HANDLE_NEXT_LETTER,
    SMTP_FSM_EV_HANDLE_NEW_LETTER,
    SMTP_FSM_EV_HANDLE_SEND_RSET,
    SMTP_FSM_EV_HANDLE_RSET_RESPONSE,
    SMTP_FSM_EV_HANDLE_ERROR,
    SMTP_FSM_EV_INVALID
} te_smtp_fsm_event;

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  SMTP_FSM_ST_DONE or SMTP_FSM_ST_INVALID, it resets to
 *  SMTP_FSM_ST_INIT and returns SMTP_FSM_ST_INIT.
 */
extern te_smtp_fsm_state
smtp_fsm_step(
    te_smtp_fsm_state smtp_fsm_state,
    te_smtp_fsm_event trans_evt,
    const char *cmd,
    void *state );

#endif /* AUTOFSM_AUTOGEN_FSM_H_GUARD */
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of autogen-fsm.h */
