#ifndef STATES_H
#define STATES_H

//======================//
//       CONTEXT        //
//======================//

#define NULL_POINTER - 100

#define SMTP_ERROR -1

#define PREPARE_SOCKET_CONNECTION 0
#define RECEIVE_SMTP_GREETING 1
#define SEND_EHLO 2
#define RECEIVE_EHLO_RESPONSE 3
#define SEND_MAIL_FROM 4
#define RECEIVE_MAIL_FROM_RESPONSE 5
#define SEND_RCPT_TO 6
#define RECEIVE_RCPT_TO_RESPONSE 7
#define SEND_DATA 8
#define RECEIVE_DATA_RESPONSE 9
#define SEND_LETTER 10
#define RECEIVE_LETTER_RESPONSE 11
#define SEND_QUIT 12
#define RECEIVE_QUIT_RESPONSE 13
#define DISPOSING_SOCKET 14

#define SEND_RSET 20
#define RECEIVE_RSET_RESPONSE 21


#endif // STATES_H